apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.0/manifests/install.yaml

namespace: argocd

labels:
  - pairs:
      app.kubernetes.io/name: argocd
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/managed-by: kustomize